### ISSUE TITLE
IronJS fails to compile on Mono 2.10 

### ISSUE THREAD

**Issue by wesleywiser** [fholm/IronJS#42]
When compiling IronJS on Mono 2.10, the F# compiler reports the following error:

```
typecheck error FS0501: The member or object constructor 'TryParse' takes 2 argument(s) but is here given 4. The required signature is 'Numerics.BigInteger.TryParse(value: string, result: byref<Numerics.BigInteger>) : bool'.
```

at these locations:
\IronJS\Src\IronJS\Runtime.fs(2385,14,2385,66)
\IronJS\Src\IronJS\Compiler.Parser.fs(216,12,216,77)
\IronJS\Src\IronJS\Compiler.Parser.fs(235,12,235,77)

Looks like the [mono implementation of BigInteger](https://github.com/mono/mono/blob/mono-2-10/mcs/class/System.Numerics/System.Numerics/BigInteger.cs) doesn't have the `BigInteger.TryParse(string, NumberStyles, IFormatProvider, out BigInteger)` overload, although it does have `BigInteger.TryParse(string, out BigInteger)`.

**Comment by fholm** [comment]
The reason for this is that I renamed a bunch of compile time constants the head master branch a couple of commits back and forgot to update the build script. Will be fixed within the new few days.
